## YAML Override template
## original/file.tpl: override/file.tpl
---
# version 1
#system/AdminModule/Resources/views/AdminInterface/header.html.twig: themes/AdminLTETheme/Resources/KaikmediaAdminModule/views/AdminInterface/header.html.twig
#system/AdminModule/Resources/views/AdminInterface/modules.panel.html.twig: themes/AdminLTETheme/Resources/KaikmediaAdminModule/views/AdminInterface/modules.panel.html.twig
#system/AdminModule/Resources/views/AdminInterface/categories.panel.html.twig: themes/AdminLTETheme/Resources/KaikmediaAdminModule/views/AdminInterface/categories.panel.html.twig
#version 2
#system/AdminModule/Resources/views/AdminInterface/header.html.twig: themes/kaikmedia/adminlte-theme/Resources/KaikmediaAdminModule/views/AdminInterface/header.html.twig
#system/AdminModule/Resources/views/AdminInterface/modules.panel.html.twig: themes/kaikmedia/adminlte-theme/Resources/KaikmediaAdminModule/views/AdminInterface/modules.panel.html.twig
#system/AdminModule/Resources/views/AdminInterface/categories.panel.html.twig: themes/kaikmedia/adminlte-theme/Resources/KaikmediaAdminModule/views/AdminInterface/categories.panel.html.twig
#system/AdminModule/Resources/views/AdminInterface/breadCrumbs.html.twig: themes/kaikmedia/adminlte-theme/Resources/KaikmediaAdminModule/views/AdminInterface/breadCrumbs.html.twig.html.twig