## YAML Override template
## original/file.tpl: override/file.tpl
---
system/AdminModule/Resources/views/AdminInterface/header.html.twig: themes/AdminLTETheme/Resources/ZikulaAdminModule/views/AdminInterface/header.html.twig
system/AdminModule/Resources/views/AdminInterface/modules.panel.html.twig: themes/AdminLTETheme/Resources/ZikulaAdminModule/views/AdminInterface/modules.panel.html.twig
system/AdminModule/Resources/views/AdminInterface/categories.panel.html.twig: themes/AdminLTETheme/Resources/ZikulaAdminModule/views/AdminInterface/categories.panel.html.twig
