##
# KaikmediaAdminLTETheme variables
##
layout:
  default_value: 
  type: choice
  options:
    choices:
      default: Default
      layout-top-nav: Top Navigation
      layout-boxed: Boxed
      fixed: Fixed
      sidebar-collapse: Collapsed sidebar
skin:
  default_value: skin-blue
  type: choice
  options:
    choices:
      skin-blue: Blue
      skin-blue-light: Blue light
      skin-yellow: Yellow
      skin-yellow-light: Yellow light
      skin-green: Green
      skin-green-light: Green light
      skin-purple: Purple
      skin-purple-light: Purple light      
      skin-red: Red
      skin-red-light: Red light
      skin-black: Black
      skin-black-light: Black light      
home:
  default_value: 1col
  type: choice
  options:
    choices:
      1col: 1 Column  
master:
  default_value: 1col
  type: choice
  options:
    choices:
      1col: 1 Column
admin:
  default_value: 1col
  type: choice
  options:
    choices:
      1col: 1 Column